version: '3.8'

services:
  db_tasks:
    container_name: todo_tasks_pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    networks:
      - todo-compose-network

  db_users:
    container_name: todo_users_pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    networks:
      - todo-compose-network

  pgadmin:
    container_name: todo_pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - todo-compose-network
  rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      ports:
        - "5672:5672"
        - "15672:15672"

networks: 
  todo-compose-network:
    driver: bridge
